# Image Study Example 6-1

## Numpy는 Matrix 등의 행렬 연산이다

In [1]:
import numpy as np

numpy에서 제공하는 array(Matlab의 Matrix와 같은)를 사용해서 3x3 Image X를 초기화한다

In [7]:
X = np.array([[200, 100, 100], [0, 10, 50], [50, 250, 120]])
print(X)

[[200 100 100]
 [  0  10  50]
 [ 50 250 120]]


Y도 마찬가지

In [9]:
Y = np.array([[100, 220, 230], [45, 95, 120], [205, 100, 0]])
print(Y)

[[100 220 230]
 [ 45  95 120]
 [205 100   0]]


W = X+Y

In [10]:
W = X + Y
print(W)

[[300 320 330]
 [ 45 105 170]
 [255 350 120]]


#### Normalization 방법 1. 최대값과 최소값을 이용한 방법
#### 수식은 교재에 있다
#### min(), max(), round()는 numpy에서 제공하는 함수이다

In [12]:
Za = np.round(255*(W-W.min())/(W.max()-W.min()))

astype 함수는 자료형을 변경해 준다 (double -> uint8)

In [14]:
Za = Za.astype(dtype='uint8')
print(Za)

[[213 230 238]
 [  0  50 105]
 [176 255  63]]


#### Normalization 방법 2. 0-255로 강제로 자르기
#### clip 하한/상한 값으로 값을 Truncate해주는 함수이다

In [15]:
Zb = np.clip(W,0,255)
print(Zb)

[[255 255 255]
 [ 45 105 170]
 [255 255 120]]
